require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe("/school_classes", type: :request) do
  # SchoolClass. As you add validations to SchoolClass, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
      name: "3 ano 3",
    }
  }

  let(:invalid_attributes) {
    {
      name: "",
    }
  }

  describe "GET /index" do
    it "renders a successful response" do
      SchoolClass.create!(valid_attributes)
      get school_classes_url
      expect(response).to(be_successful)
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      school_class = SchoolClass.create!(valid_attributes)
      get school_class_url(school_class)
      expect(response).to(be_successful)
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_school_class_url
      expect(response).to(be_successful)
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      school_class = SchoolClass.create!(valid_attributes)
      get edit_school_class_url(school_class)
      expect(response).to(be_successful)
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SchoolClass" do
        expect {
          post(school_classes_url, params: { school_class: valid_attributes })
        }.to(change(SchoolClass, :count).by(1))
      end

      it "redirects to the created school_class" do
        post school_classes_url, params: { school_class: valid_attributes }
        expect(response).to(redirect_to(school_class_url(SchoolClass.last)))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SchoolClass" do
        expect {
          post(school_classes_url, params: { school_class: invalid_attributes })
        }.to(change(SchoolClass, :count).by(0))
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post school_classes_url, params: { school_class: invalid_attributes }
        expect(response).to(have_http_status(:unprocessable_entity))
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        {
          name: "CC3A34",
        }
      }

      it "updates the requested school_class" do
        school_class = SchoolClass.create!(valid_attributes)
        patch school_class_url(school_class), params: { school_class: new_attributes }
        school_class.reload
        expect(school_class.name).to(eq("CC3A34"))
      end

      it "redirects to the school_class" do
        school_class = SchoolClass.create!(valid_attributes)
        patch school_class_url(school_class), params: { school_class: new_attributes }
        school_class.reload
        expect(response).to(redirect_to(school_class_url(school_class)))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        school_class = SchoolClass.create!(valid_attributes)
        patch school_class_url(school_class), params: { school_class: invalid_attributes }
        expect(response).to(have_http_status(:unprocessable_entity))
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested school_class" do
      school_class = SchoolClass.create!(valid_attributes)
      expect {
        delete(school_class_url(school_class))
      }.to(change(SchoolClass, :count).by(-1))
    end

    it "redirects to the school_classes list" do
      school_class = SchoolClass.create!(valid_attributes)
      delete school_class_url(school_class)
      expect(response).to(redirect_to(school_classes_url))
    end
  end
end
